stages:
  - test
  - deploy

test:
  stage: test
  before_script:
    - cd backend
  script:
    - go test ./...
  after_script:
    - cd ..

build-and-deploy:
  stage: deploy
  script:
  - curl -k -X POST $PORTAINER_HOOK
