{
 "title": "Pixcelbattle dashboard",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  { "title": "Метрики", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Всего поставлено пикселей",
   "type": "stat",
   "gridPos": { "h": 6, "w": 5, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "pixels_placed_total", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Пиксели в минуту",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 14, "x": 5, "y": 1 },
   "targets": [
    { "expr": "rate(pixels_placed_total[1m])", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Активные пользователи",
   "type": "stat",
   "gridPos": { "h": 6, "w": 5, "x": 19, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "active_connections", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Количествово ошибок",
   "type": "stat",
   "gridPos": { "h": 6, "w": 5, "x": 0, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "pixel_errors_total", "legendFormat": "__auto" }
   ]
  },
  {
   "title": " Гистограмма времени отклика",
   "type": "histogram",
   "gridPos": { "h": 6, "w": 14, "x": 5, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "http_request_duration_seconds_bucket",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Среднее время отклика",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 5, "x": 19, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(http_request_duration_seconds_sum[1m])) / sum(rate(http_request_duration_seconds_count[1m]))\n",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Системные метрики", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 } },
  {
   "title": "Потребление памяти",
   "type": "stat",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "go_memstats_alloc_bytes", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Количество горутин",
   "type": "stat",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "go_goroutines", "legendFormat": "__auto" }
   ]
  }
 ]
}