version: '3.8'

services:
  server:
    build: 
      context: .
      dockerfile: Dockerfile
    
    ports:
      - "8080:8080"
    container_name: pixcel-server
    environment:
      - CONFIG_PATH=./internal/config
    restart: on-failure