enviroment: dev
server:
  host: "0.0.0.0"
  port: 8080
  timeout: 10s
  idle_timeout: 60s

redis:
  host: "redis"
  port: 6379
  db: 0
  max_retries: 5
  dial_timeout: 10s
  timeout: 5s

nats:
  url: "nats://nats:4222"
